// SPDX-License-Identifier: BSD-2-Clause
//
// Copyright 2019 FRRouting
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
// this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
// notice, this list of conditions and the following disclaimer in the
// documentation and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
// BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
// OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
// THE POSSIBILITY OF SUCH DAMAGE.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: frr-northbound.proto

package frr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Supported encodings for YANG instance data.
type Encoding int32

const (
	Encoding_JSON Encoding = 0
	Encoding_XML  Encoding = 1
)

// Enum value maps for Encoding.
var (
	Encoding_name = map[int32]string{
		0: "JSON",
		1: "XML",
	}
	Encoding_value = map[string]int32{
		"JSON": 0,
		"XML":  1,
	}
)

func (x Encoding) Enum() *Encoding {
	p := new(Encoding)
	*p = x
	return p
}

func (x Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_frr_northbound_proto_enumTypes[0].Descriptor()
}

func (Encoding) Type() protoreflect.EnumType {
	return &file_frr_northbound_proto_enumTypes[0]
}

func (x Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encoding.Descriptor instead.
func (Encoding) EnumDescriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{0}
}

// Type of elements within the data tree.
type GetRequest_DataType int32

const (
	// All data elements.
	GetRequest_ALL GetRequest_DataType = 0
	// Config elements.
	GetRequest_CONFIG GetRequest_DataType = 1
	// State elements.
	GetRequest_STATE GetRequest_DataType = 2
)

// Enum value maps for GetRequest_DataType.
var (
	GetRequest_DataType_name = map[int32]string{
		0: "ALL",
		1: "CONFIG",
		2: "STATE",
	}
	GetRequest_DataType_value = map[string]int32{
		"ALL":    0,
		"CONFIG": 1,
		"STATE":  2,
	}
)

func (x GetRequest_DataType) Enum() *GetRequest_DataType {
	p := new(GetRequest_DataType)
	*p = x
	return p
}

func (x GetRequest_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetRequest_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_frr_northbound_proto_enumTypes[1].Descriptor()
}

func (GetRequest_DataType) Type() protoreflect.EnumType {
	return &file_frr_northbound_proto_enumTypes[1]
}

func (x GetRequest_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetRequest_DataType.Descriptor instead.
func (GetRequest_DataType) EnumDescriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{2, 0}
}

type LoadToCandidateRequest_LoadType int32

const (
	// Merge the data tree into the candidate configuration.
	LoadToCandidateRequest_MERGE LoadToCandidateRequest_LoadType = 0
	// Replace the candidate configuration by the provided data tree.
	LoadToCandidateRequest_REPLACE LoadToCandidateRequest_LoadType = 1
)

// Enum value maps for LoadToCandidateRequest_LoadType.
var (
	LoadToCandidateRequest_LoadType_name = map[int32]string{
		0: "MERGE",
		1: "REPLACE",
	}
	LoadToCandidateRequest_LoadType_value = map[string]int32{
		"MERGE":   0,
		"REPLACE": 1,
	}
)

func (x LoadToCandidateRequest_LoadType) Enum() *LoadToCandidateRequest_LoadType {
	p := new(LoadToCandidateRequest_LoadType)
	*p = x
	return p
}

func (x LoadToCandidateRequest_LoadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadToCandidateRequest_LoadType) Descriptor() protoreflect.EnumDescriptor {
	return file_frr_northbound_proto_enumTypes[2].Descriptor()
}

func (LoadToCandidateRequest_LoadType) Type() protoreflect.EnumType {
	return &file_frr_northbound_proto_enumTypes[2]
}

func (x LoadToCandidateRequest_LoadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadToCandidateRequest_LoadType.Descriptor instead.
func (LoadToCandidateRequest_LoadType) EnumDescriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{12, 0}
}

type CommitRequest_Phase int32

const (
	// Validate if the configuration changes are valid (phase 0).
	CommitRequest_VALIDATE CommitRequest_Phase = 0
	// Prepare resources to apply the configuration changes (phase 1).
	CommitRequest_PREPARE CommitRequest_Phase = 1
	// Release previously allocated resources (phase 2).
	CommitRequest_ABORT CommitRequest_Phase = 2
	// Apply the configuration changes (phase 2).
	CommitRequest_APPLY CommitRequest_Phase = 3
	// All of the above (VALIDATE + PREPARE + ABORT/APPLY).
	//
	// This option can't be used to implement network-wide transactions,
	// since they require the manager entity to take into account the results
	// of the preparation phase of multiple managed devices.
	CommitRequest_ALL CommitRequest_Phase = 4
)

// Enum value maps for CommitRequest_Phase.
var (
	CommitRequest_Phase_name = map[int32]string{
		0: "VALIDATE",
		1: "PREPARE",
		2: "ABORT",
		3: "APPLY",
		4: "ALL",
	}
	CommitRequest_Phase_value = map[string]int32{
		"VALIDATE": 0,
		"PREPARE":  1,
		"ABORT":    2,
		"APPLY":    3,
		"ALL":      4,
	}
)

func (x CommitRequest_Phase) Enum() *CommitRequest_Phase {
	p := new(CommitRequest_Phase)
	*p = x
	return p
}

func (x CommitRequest_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommitRequest_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_frr_northbound_proto_enumTypes[3].Descriptor()
}

func (CommitRequest_Phase) Type() protoreflect.EnumType {
	return &file_frr_northbound_proto_enumTypes[3]
}

func (x CommitRequest_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommitRequest_Phase.Descriptor instead.
func (CommitRequest_Phase) EnumDescriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{14, 0}
}

// RPC: GetCapabilities()
type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{0}
}

type GetCapabilitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// FRR version.
	FrrVersion string `protobuf:"bytes,1,opt,name=frr_version,json=frrVersion,proto3" json:"frr_version,omitempty"`
	// Indicates whether FRR was compiled with support for configuration
	// rollbacks or not (--enable-config-rollbacks).
	RollbackSupport bool `protobuf:"varint,2,opt,name=rollback_support,json=rollbackSupport,proto3" json:"rollback_support,omitempty"`
	// Supported schema modules.
	SupportedModules []*ModuleData `protobuf:"bytes,3,rep,name=supported_modules,json=supportedModules,proto3" json:"supported_modules,omitempty"`
	// Supported encodings.
	SupportedEncodings []Encoding `protobuf:"varint,4,rep,packed,name=supported_encodings,json=supportedEncodings,proto3,enum=frr.Encoding" json:"supported_encodings,omitempty"`
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{1}
}

func (x *GetCapabilitiesResponse) GetFrrVersion() string {
	if x != nil {
		return x.FrrVersion
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetRollbackSupport() bool {
	if x != nil {
		return x.RollbackSupport
	}
	return false
}

func (x *GetCapabilitiesResponse) GetSupportedModules() []*ModuleData {
	if x != nil {
		return x.SupportedModules
	}
	return nil
}

func (x *GetCapabilitiesResponse) GetSupportedEncodings() []Encoding {
	if x != nil {
		return x.SupportedEncodings
	}
	return nil
}

// RPC: Get()
type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of data being requested.
	Type GetRequest_DataType `protobuf:"varint,1,opt,name=type,proto3,enum=frr.GetRequest_DataType" json:"type,omitempty"`
	// Encoding to be used.
	Encoding Encoding `protobuf:"varint,2,opt,name=encoding,proto3,enum=frr.Encoding" json:"encoding,omitempty"`
	// Include implicit default nodes.
	WithDefaults bool `protobuf:"varint,3,opt,name=with_defaults,json=withDefaults,proto3" json:"with_defaults,omitempty"`
	// Paths requested by the client.
	Path []string `protobuf:"bytes,4,rep,name=path,proto3" json:"path,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetType() GetRequest_DataType {
	if x != nil {
		return x.Type
	}
	return GetRequest_ALL
}

func (x *GetRequest) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_JSON
}

func (x *GetRequest) GetWithDefaults() bool {
	if x != nil {
		return x.WithDefaults
	}
	return false
}

func (x *GetRequest) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Timestamp in nanoseconds since Epoch.
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The requested data.
	Data *DataTree `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetResponse) GetData() *DataTree {
	if x != nil {
		return x.Data
	}
	return nil
}

// RPC: CreateCandidate()
type CreateCandidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateCandidateRequest) Reset() {
	*x = CreateCandidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCandidateRequest) ProtoMessage() {}

func (x *CreateCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCandidateRequest.ProtoReflect.Descriptor instead.
func (*CreateCandidateRequest) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{4}
}

type CreateCandidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Handle to the new created candidate configuration.
	CandidateId uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
}

func (x *CreateCandidateResponse) Reset() {
	*x = CreateCandidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCandidateResponse) ProtoMessage() {}

func (x *CreateCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCandidateResponse.ProtoReflect.Descriptor instead.
func (*CreateCandidateResponse) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCandidateResponse) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

// RPC: DeleteCandidate()
type DeleteCandidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Candidate configuration to delete.
	CandidateId uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
}

func (x *DeleteCandidateRequest) Reset() {
	*x = DeleteCandidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCandidateRequest) ProtoMessage() {}

func (x *DeleteCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCandidateRequest.ProtoReflect.Descriptor instead.
func (*DeleteCandidateRequest) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCandidateRequest) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

type DeleteCandidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCandidateResponse) Reset() {
	*x = DeleteCandidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCandidateResponse) ProtoMessage() {}

func (x *DeleteCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCandidateResponse.ProtoReflect.Descriptor instead.
func (*DeleteCandidateResponse) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{7}
}

// RPC: UpdateCandidate()
type UpdateCandidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Candidate configuration to update.
	CandidateId uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
}

func (x *UpdateCandidateRequest) Reset() {
	*x = UpdateCandidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCandidateRequest) ProtoMessage() {}

func (x *UpdateCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCandidateRequest.ProtoReflect.Descriptor instead.
func (*UpdateCandidateRequest) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCandidateRequest) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

type UpdateCandidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCandidateResponse) Reset() {
	*x = UpdateCandidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCandidateResponse) ProtoMessage() {}

func (x *UpdateCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCandidateResponse.ProtoReflect.Descriptor instead.
func (*UpdateCandidateResponse) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{9}
}

// RPC: EditCandidate()
type EditCandidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Candidate configuration that is going to be edited.
	CandidateId uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	// Data elements to be created or updated.
	Update []*PathValue `protobuf:"bytes,2,rep,name=update,proto3" json:"update,omitempty"`
	// Paths to be deleted from the data tree.
	Delete []*PathValue `protobuf:"bytes,3,rep,name=delete,proto3" json:"delete,omitempty"`
}

func (x *EditCandidateRequest) Reset() {
	*x = EditCandidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCandidateRequest) ProtoMessage() {}

func (x *EditCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCandidateRequest.ProtoReflect.Descriptor instead.
func (*EditCandidateRequest) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{10}
}

func (x *EditCandidateRequest) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *EditCandidateRequest) GetUpdate() []*PathValue {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *EditCandidateRequest) GetDelete() []*PathValue {
	if x != nil {
		return x.Delete
	}
	return nil
}

type EditCandidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EditCandidateResponse) Reset() {
	*x = EditCandidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCandidateResponse) ProtoMessage() {}

func (x *EditCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCandidateResponse.ProtoReflect.Descriptor instead.
func (*EditCandidateResponse) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{11}
}

// RPC: LoadToCandidate()
type LoadToCandidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Candidate configuration that is going to be edited.
	CandidateId uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	// Load operation to apply.
	Type LoadToCandidateRequest_LoadType `protobuf:"varint,2,opt,name=type,proto3,enum=frr.LoadToCandidateRequest_LoadType" json:"type,omitempty"`
	// Configuration data.
	Config *DataTree `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *LoadToCandidateRequest) Reset() {
	*x = LoadToCandidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadToCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadToCandidateRequest) ProtoMessage() {}

func (x *LoadToCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadToCandidateRequest.ProtoReflect.Descriptor instead.
func (*LoadToCandidateRequest) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{12}
}

func (x *LoadToCandidateRequest) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *LoadToCandidateRequest) GetType() LoadToCandidateRequest_LoadType {
	if x != nil {
		return x.Type
	}
	return LoadToCandidateRequest_MERGE
}

func (x *LoadToCandidateRequest) GetConfig() *DataTree {
	if x != nil {
		return x.Config
	}
	return nil
}

type LoadToCandidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoadToCandidateResponse) Reset() {
	*x = LoadToCandidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadToCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadToCandidateResponse) ProtoMessage() {}

func (x *LoadToCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadToCandidateResponse.ProtoReflect.Descriptor instead.
func (*LoadToCandidateResponse) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{13}
}

// RPC: Commit()
type CommitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Candidate configuration that is going to be committed.
	CandidateId uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	// Transaction phase.
	Phase CommitRequest_Phase `protobuf:"varint,2,opt,name=phase,proto3,enum=frr.CommitRequest_Phase" json:"phase,omitempty"`
	// Assign a comment to this commit.
	Comment string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{14}
}

func (x *CommitRequest) GetCandidateId() uint32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *CommitRequest) GetPhase() CommitRequest_Phase {
	if x != nil {
		return x.Phase
	}
	return CommitRequest_VALIDATE
}

func (x *CommitRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CommitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID of the created configuration transaction (when the phase is APPLY
	// or ALL).
	TransactionId uint32 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Human-readable error or warning message(s).
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{15}
}

func (x *CommitResponse) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *CommitResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// RPC: ListTransactions()
type ListTransactionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{16}
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Transaction ID.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Client that committed the transaction.
	Client string `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	// Date and time the transaction was committed.
	Date string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	// Comment assigned to the transaction.
	Comment string `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{17}
}

func (x *ListTransactionsResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListTransactionsResponse) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *ListTransactionsResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ListTransactionsResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// RPC: GetTransaction()
type GetTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Transaction to retrieve.
	TransactionId uint32 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Encoding to be used.
	Encoding Encoding `protobuf:"varint,2,opt,name=encoding,proto3,enum=frr.Encoding" json:"encoding,omitempty"`
	// Include implicit default nodes.
	WithDefaults bool `protobuf:"varint,3,opt,name=with_defaults,json=withDefaults,proto3" json:"with_defaults,omitempty"`
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{18}
}

func (x *GetTransactionRequest) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *GetTransactionRequest) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_JSON
}

func (x *GetTransactionRequest) GetWithDefaults() bool {
	if x != nil {
		return x.WithDefaults
	}
	return false
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *DataTree `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{19}
}

func (x *GetTransactionResponse) GetConfig() *DataTree {
	if x != nil {
		return x.Config
	}
	return nil
}

// RPC: LockConfig()
type LockConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LockConfigRequest) Reset() {
	*x = LockConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockConfigRequest) ProtoMessage() {}

func (x *LockConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockConfigRequest.ProtoReflect.Descriptor instead.
func (*LockConfigRequest) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{20}
}

type LockConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LockConfigResponse) Reset() {
	*x = LockConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockConfigResponse) ProtoMessage() {}

func (x *LockConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockConfigResponse.ProtoReflect.Descriptor instead.
func (*LockConfigResponse) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{21}
}

// RPC: UnlockConfig()
type UnlockConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnlockConfigRequest) Reset() {
	*x = UnlockConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlockConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockConfigRequest) ProtoMessage() {}

func (x *UnlockConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockConfigRequest.ProtoReflect.Descriptor instead.
func (*UnlockConfigRequest) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{22}
}

type UnlockConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnlockConfigResponse) Reset() {
	*x = UnlockConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlockConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockConfigResponse) ProtoMessage() {}

func (x *UnlockConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockConfigResponse.ProtoReflect.Descriptor instead.
func (*UnlockConfigResponse) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{23}
}

// RPC: Execute()
type ExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Path of the YANG RPC or YANG Action.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Input parameters.
	Input []*PathValue `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty"`
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{24}
}

func (x *ExecuteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExecuteRequest) GetInput() []*PathValue {
	if x != nil {
		return x.Input
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Output parameters.
	Output []*PathValue `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"`
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{25}
}

func (x *ExecuteResponse) GetOutput() []*PathValue {
	if x != nil {
		return x.Output
	}
	return nil
}

// YANG module.
type ModuleData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the YANG module;
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Organization publishing the module.
	Organization string `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	// Latest revision of the module;
	Revision string `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
}

func (x *ModuleData) Reset() {
	*x = ModuleData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleData) ProtoMessage() {}

func (x *ModuleData) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleData.ProtoReflect.Descriptor instead.
func (*ModuleData) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{26}
}

func (x *ModuleData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleData) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *ModuleData) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

// Path-value pair representing a data element.
type PathValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// YANG data path.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Data value.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PathValue) Reset() {
	*x = PathValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathValue) ProtoMessage() {}

func (x *PathValue) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathValue.ProtoReflect.Descriptor instead.
func (*PathValue) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{27}
}

func (x *PathValue) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PathValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// YANG instance data.
type DataTree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encoding Encoding `protobuf:"varint,1,opt,name=encoding,proto3,enum=frr.Encoding" json:"encoding,omitempty"`
	Data     string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DataTree) Reset() {
	*x = DataTree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_northbound_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTree) ProtoMessage() {}

func (x *DataTree) ProtoReflect() protoreflect.Message {
	mi := &file_frr_northbound_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTree.ProtoReflect.Descriptor instead.
func (*DataTree) Descriptor() ([]byte, []int) {
	return file_frr_northbound_proto_rawDescGZIP(), []int{28}
}

func (x *DataTree) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_JSON
}

func (x *DataTree) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_frr_northbound_proto protoreflect.FileDescriptor

var file_frr_northbound_proto_rawDesc = []byte{
	0x0a, 0x14, 0x66, 0x72, 0x72, 0x2d, 0x6e, 0x6f, 0x72, 0x74, 0x68, 0x62, 0x6f, 0x75, 0x6e, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x66, 0x72, 0x72, 0x22, 0x18, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xe3, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x72, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x73,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x72, 0x6f,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x3c, 0x0a,
	0x11, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x10, 0x73, 0x75, 0x70, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x13, 0x73,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e,
	0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x45,
	0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x12, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x22, 0xca, 0x01, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x65, 0x6e, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x66, 0x72, 0x72,
	0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64,
	0x69, 0x6e, 0x67, 0x12, 0x23, 0x0a, 0x0d, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x77, 0x69, 0x74, 0x68,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x2a, 0x0a, 0x08,
	0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x02, 0x22, 0x4e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72,
	0x65, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x3c, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x22, 0x3b, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x22, 0x19, 0x0a,
	0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3b, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x89, 0x01, 0x0a, 0x14, 0x45, 0x64, 0x69, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x06,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66,
	0x72, 0x72, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x17, 0x0a, 0x15,
	0x45, 0x64, 0x69, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xc0, 0x01, 0x0a, 0x16, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x6f,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x24, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x6f, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c,
	0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x66, 0x72, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x65, 0x65, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x22, 0x22, 0x0a, 0x08, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x09, 0x0a, 0x05, 0x4d, 0x45, 0x52, 0x47, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52,
	0x45, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x10, 0x01, 0x22, 0x19, 0x0a, 0x17, 0x4c, 0x6f, 0x61, 0x64,
	0x54, 0x6f, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x68, 0x61, 0x73,
	0x65, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x41, 0x0a, 0x05, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x45,
	0x50, 0x41, 0x52, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x10,
	0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x50, 0x50, 0x4c, 0x59, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03,
	0x41, 0x4c, 0x4c, 0x10, 0x04, 0x22, 0x5c, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x70,
	0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x22, 0x8e, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x29, 0x0a, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69,
	0x6e, 0x67, 0x52, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x23, 0x0a, 0x0d,
	0x77, 0x69, 0x74, 0x68, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x77, 0x69, 0x74, 0x68, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x73, 0x22, 0x3f, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x66, 0x72,
	0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x65, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x6f, 0x63, 0x6b, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x0a,
	0x13, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4a, 0x0a, 0x0e,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x24, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x39, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x72,
	0x72, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x22, 0x60, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x76,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x35, 0x0a, 0x09, 0x50, 0x61, 0x74, 0x68, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x49, 0x0a, 0x08,
	0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x65, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x65, 0x6e, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x66, 0x72, 0x72,
	0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64,
	0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x1d, 0x0a, 0x08, 0x45, 0x6e, 0x63, 0x6f, 0x64,
	0x69, 0x6e, 0x67, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x58, 0x4d, 0x4c, 0x10, 0x01, 0x32, 0xab, 0x07, 0x0a, 0x0a, 0x4e, 0x6f, 0x72, 0x74, 0x68,
	0x62, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x4e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x66,
	0x72, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x66, 0x72, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x4e, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0d, 0x45, 0x64, 0x69, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x43,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a,
	0x0f, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x1b, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x66, 0x72, 0x72, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x33, 0x0a,
	0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x66, 0x72,
	0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x53, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x66, 0x72, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a, 0x4c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x16, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x66, 0x72, 0x72,
	0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x55, 0x6e, 0x6c, 0x6f,
	0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x07,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x66, 0x72, 0x72, 0x2e, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x66,
	0x72, 0x72, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x66, 0x72, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_frr_northbound_proto_rawDescOnce sync.Once
	file_frr_northbound_proto_rawDescData = file_frr_northbound_proto_rawDesc
)

func file_frr_northbound_proto_rawDescGZIP() []byte {
	file_frr_northbound_proto_rawDescOnce.Do(func() {
		file_frr_northbound_proto_rawDescData = protoimpl.X.CompressGZIP(file_frr_northbound_proto_rawDescData)
	})
	return file_frr_northbound_proto_rawDescData
}

var file_frr_northbound_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_frr_northbound_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_frr_northbound_proto_goTypes = []interface{}{
	(Encoding)(0),                        // 0: frr.Encoding
	(GetRequest_DataType)(0),             // 1: frr.GetRequest.DataType
	(LoadToCandidateRequest_LoadType)(0), // 2: frr.LoadToCandidateRequest.LoadType
	(CommitRequest_Phase)(0),             // 3: frr.CommitRequest.Phase
	(*GetCapabilitiesRequest)(nil),       // 4: frr.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil),      // 5: frr.GetCapabilitiesResponse
	(*GetRequest)(nil),                   // 6: frr.GetRequest
	(*GetResponse)(nil),                  // 7: frr.GetResponse
	(*CreateCandidateRequest)(nil),       // 8: frr.CreateCandidateRequest
	(*CreateCandidateResponse)(nil),      // 9: frr.CreateCandidateResponse
	(*DeleteCandidateRequest)(nil),       // 10: frr.DeleteCandidateRequest
	(*DeleteCandidateResponse)(nil),      // 11: frr.DeleteCandidateResponse
	(*UpdateCandidateRequest)(nil),       // 12: frr.UpdateCandidateRequest
	(*UpdateCandidateResponse)(nil),      // 13: frr.UpdateCandidateResponse
	(*EditCandidateRequest)(nil),         // 14: frr.EditCandidateRequest
	(*EditCandidateResponse)(nil),        // 15: frr.EditCandidateResponse
	(*LoadToCandidateRequest)(nil),       // 16: frr.LoadToCandidateRequest
	(*LoadToCandidateResponse)(nil),      // 17: frr.LoadToCandidateResponse
	(*CommitRequest)(nil),                // 18: frr.CommitRequest
	(*CommitResponse)(nil),               // 19: frr.CommitResponse
	(*ListTransactionsRequest)(nil),      // 20: frr.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),     // 21: frr.ListTransactionsResponse
	(*GetTransactionRequest)(nil),        // 22: frr.GetTransactionRequest
	(*GetTransactionResponse)(nil),       // 23: frr.GetTransactionResponse
	(*LockConfigRequest)(nil),            // 24: frr.LockConfigRequest
	(*LockConfigResponse)(nil),           // 25: frr.LockConfigResponse
	(*UnlockConfigRequest)(nil),          // 26: frr.UnlockConfigRequest
	(*UnlockConfigResponse)(nil),         // 27: frr.UnlockConfigResponse
	(*ExecuteRequest)(nil),               // 28: frr.ExecuteRequest
	(*ExecuteResponse)(nil),              // 29: frr.ExecuteResponse
	(*ModuleData)(nil),                   // 30: frr.ModuleData
	(*PathValue)(nil),                    // 31: frr.PathValue
	(*DataTree)(nil),                     // 32: frr.DataTree
}
var file_frr_northbound_proto_depIdxs = []int32{
	30, // 0: frr.GetCapabilitiesResponse.supported_modules:type_name -> frr.ModuleData
	0,  // 1: frr.GetCapabilitiesResponse.supported_encodings:type_name -> frr.Encoding
	1,  // 2: frr.GetRequest.type:type_name -> frr.GetRequest.DataType
	0,  // 3: frr.GetRequest.encoding:type_name -> frr.Encoding
	32, // 4: frr.GetResponse.data:type_name -> frr.DataTree
	31, // 5: frr.EditCandidateRequest.update:type_name -> frr.PathValue
	31, // 6: frr.EditCandidateRequest.delete:type_name -> frr.PathValue
	2,  // 7: frr.LoadToCandidateRequest.type:type_name -> frr.LoadToCandidateRequest.LoadType
	32, // 8: frr.LoadToCandidateRequest.config:type_name -> frr.DataTree
	3,  // 9: frr.CommitRequest.phase:type_name -> frr.CommitRequest.Phase
	0,  // 10: frr.GetTransactionRequest.encoding:type_name -> frr.Encoding
	32, // 11: frr.GetTransactionResponse.config:type_name -> frr.DataTree
	31, // 12: frr.ExecuteRequest.input:type_name -> frr.PathValue
	31, // 13: frr.ExecuteResponse.output:type_name -> frr.PathValue
	0,  // 14: frr.DataTree.encoding:type_name -> frr.Encoding
	4,  // 15: frr.Northbound.GetCapabilities:input_type -> frr.GetCapabilitiesRequest
	6,  // 16: frr.Northbound.Get:input_type -> frr.GetRequest
	8,  // 17: frr.Northbound.CreateCandidate:input_type -> frr.CreateCandidateRequest
	10, // 18: frr.Northbound.DeleteCandidate:input_type -> frr.DeleteCandidateRequest
	12, // 19: frr.Northbound.UpdateCandidate:input_type -> frr.UpdateCandidateRequest
	14, // 20: frr.Northbound.EditCandidate:input_type -> frr.EditCandidateRequest
	16, // 21: frr.Northbound.LoadToCandidate:input_type -> frr.LoadToCandidateRequest
	18, // 22: frr.Northbound.Commit:input_type -> frr.CommitRequest
	20, // 23: frr.Northbound.ListTransactions:input_type -> frr.ListTransactionsRequest
	22, // 24: frr.Northbound.GetTransaction:input_type -> frr.GetTransactionRequest
	24, // 25: frr.Northbound.LockConfig:input_type -> frr.LockConfigRequest
	26, // 26: frr.Northbound.UnlockConfig:input_type -> frr.UnlockConfigRequest
	28, // 27: frr.Northbound.Execute:input_type -> frr.ExecuteRequest
	5,  // 28: frr.Northbound.GetCapabilities:output_type -> frr.GetCapabilitiesResponse
	7,  // 29: frr.Northbound.Get:output_type -> frr.GetResponse
	9,  // 30: frr.Northbound.CreateCandidate:output_type -> frr.CreateCandidateResponse
	11, // 31: frr.Northbound.DeleteCandidate:output_type -> frr.DeleteCandidateResponse
	13, // 32: frr.Northbound.UpdateCandidate:output_type -> frr.UpdateCandidateResponse
	15, // 33: frr.Northbound.EditCandidate:output_type -> frr.EditCandidateResponse
	17, // 34: frr.Northbound.LoadToCandidate:output_type -> frr.LoadToCandidateResponse
	19, // 35: frr.Northbound.Commit:output_type -> frr.CommitResponse
	21, // 36: frr.Northbound.ListTransactions:output_type -> frr.ListTransactionsResponse
	23, // 37: frr.Northbound.GetTransaction:output_type -> frr.GetTransactionResponse
	25, // 38: frr.Northbound.LockConfig:output_type -> frr.LockConfigResponse
	27, // 39: frr.Northbound.UnlockConfig:output_type -> frr.UnlockConfigResponse
	29, // 40: frr.Northbound.Execute:output_type -> frr.ExecuteResponse
	28, // [28:41] is the sub-list for method output_type
	15, // [15:28] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_frr_northbound_proto_init() }
func file_frr_northbound_proto_init() {
	if File_frr_northbound_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_frr_northbound_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCapabilitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCapabilitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCandidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCandidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCandidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCandidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCandidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCandidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditCandidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditCandidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadToCandidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadToCandidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTransactionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTransactionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnlockConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnlockConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frr_northbound_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataTree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frr_northbound_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frr_northbound_proto_goTypes,
		DependencyIndexes: file_frr_northbound_proto_depIdxs,
		EnumInfos:         file_frr_northbound_proto_enumTypes,
		MessageInfos:      file_frr_northbound_proto_msgTypes,
	}.Build()
	File_frr_northbound_proto = out.File
	file_frr_northbound_proto_rawDesc = nil
	file_frr_northbound_proto_goTypes = nil
	file_frr_northbound_proto_depIdxs = nil
}
